# Unit tests

# Add library test subdirectories
add_subdirectory(libs/protoflow-app-registration-client)
add_subdirectory(libs/protoflow-fsm)
add_subdirectory(libs/protoflow-html-fragment)
add_subdirectory(libs/protoflow-http)
add_subdirectory(libs/protoflow-hw-client)
add_subdirectory(libs/protoflow-messaging)
add_subdirectory(libs/protoflow-logging)
add_subdirectory(libs/protoflow-rpc)
add_subdirectory(libs/protoflow-transport-tcp)
add_subdirectory(libs/protoflow-transport-unix)

